# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

default: &default
  asset_host: http://127.0.0.1:5000
  aws_s3:
    access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
    secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
    bucket_name: <%= ENV['AWS_S3_BUCKET_NAME'] %>
  branch_name: <%= ENV["BRANCH_NAME"] %>
  host: <%= ENV['APP_URL'] || ENV['HEROKU_URL'] || 'http://localhost:5000' %>
  log_level: debug
  mailer:
    smtp_settings:
      user_name: <%= ENV['MANDRILLAPP_USERNAME'] %>
      password: <%= ENV['MANDRILLAPP_PASSWORD'] %>
      address: smtp.mandrillapp.com
      port: 587
      authentication: plain
  mailer_default_from_email: "'shadowfax_app_name' <notifications@shadowfax_production_hostname>"
  mailer_delivery_method: :smtp
  rollbar_api_key: <%= ENV['ROLLBAR_ACCESS_TOKEN'] %>
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
  segment_write_key: BJbG3LZ42JVAxSpi5Rq5g3woCEOUCpix
  social:
    facebook_app_id: ENV["FACEBOOK_APP_ID"]
    facebook_app_secret: ENV["FACEBOOK_APP_SECRET"]
    google_client_id: ENV["GOOGLE_CLIENT_ID"]
    google_client_secret: ENV["GOOGLE_CLIENT_SECRET"]
    linkedin_client_id: ENV["LINKEDIN_CLIENT_ID"]
    linkedin_client_secret: ENV["LINKEDIN_CLIENT_SECRET"]
  store_uploaded_assets_in: filesystem
  subject_prefix_for_outgoing_emails: shadowfax_outgoing_emails_prefix
  support_email: support@shadowfax_production_host
  twilio:
    account_sid: <%= ENV['TWILIO_ACCOUNT_SID'] %>
    auth_token: <%= ENV['TWILIO_AUTH_TOKEN'] %>
    from_number: <%= ENV['TWILIO_FROM_NUMBER'] %>

development:
  <<: *default
  secret_key_base: 3193ce62de10f78da223e95760dd6c08523cd78204b4d8dc8bb119faf8847adceb70aadce1288ffd8e6232afb3a704c60a75feb024ab937de989322f4e64a385
  devise:
    secret_key: c0cd8c380935936ff6c6bfb7b0f0ed3f3a2d66d7d7b445394a879dea71bfb5711799c7840e7d4fd93fe8a0983c4f27fd30caebea879dff734c15ff1696262144

test:
  <<: *default
  secret_key_base: b731f261415e6f13e3e3e5a6726ee163707938f38514331fc2a67eda3800dd428bfe2a0c3b4ed83cf99e7df643e93b450511f81e05556712128ae786559ada6e
  devise:
    secret_key: 5394a879dea71bfbc0cd8c380935936ff6c6b5711799c7840e7d4fd93fe8a0983c4f27fd30caebea879dff734c15ff1696262144fb7b0f0ed3f3a2d66d7d7b44
  mailer_delivery_method: :test

staging:
  <<: *default
  secret_key_base: d731f261415e6f13e3e3e5a6726ee163707938f38514331fc2a67eda3800dd428bfe2a0c3b4ed83cf99e7df643e93b450511f81e05556712128ae786559ada6e
  devise:
    secret_key: ecd10b29124e0b3c68890e6c019566fc8a4b3f3bc519eb99d3d06d05f0a7ce3df1522472eb90e1ffc56b03119a9ed5e3e6e412bca67003c2ee449715fd98b94c
  host: <%= URI(ENV['HEROKU_URL'] || 'http://shadowfax_staging_host').host %>
  intercept_and_forward_emails_to:
    - john@example.com
    - adam@example.com
  mailer:
    smtp_settings:
      user_name: <%= ENV['MANDRILLAPP_USERNAME'] %>
      password: <%= ENV['MANDRILLAPP_PASSWORD'] %>
      domain: shadowfax_staging_host
      address: smtp.mandrillapp.com
      port: 587
      authentication: plain
      enable_starttls_auto: true
  mailer_delivery_method: :smtp
  social:
    facebook_app_id: <%= ENV["FACEBOOK_APP_ID"] %>
    facebook_app_secret: <%= ENV["FACEBOOK_APP_SECRET"] %>
    google_client_id: <%= ENV["GOOGLE_CLIENT_ID"] %>
    google_client_secret: <%= ENV["GOOGLE_CLIENT_SECRET"] %>
    linkedin_client_id: <%= ENV["LINKEDIN_CLIENT_ID"] %>
    linkedin_client_secret: <%= ENV["LINKEDIN_CLIENT_SECRET"] %>
  url_with_port: <%= ENV['HEROKU_URL'] || 'http://shadowfax_staging_host' %>

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  <<: *default
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  bcc: hello.shadowfax_app_name@gmail.com
  devise:
    secret_key: <%= ENV["DEVISE_KEY"] %>
  host: shadowfax_production_host
  mailer:
    delivery_method: :smtp
    smtp_settings:
      user_name: <%= ENV['MANDRILLAPP_USERNAME'] %>
      password: <%= ENV['MANDRILLAPP_PASSWORD'] %>
      domain: www.shadowfax_production_host
      address: smtp.mandrillapp.com
      port: 587
      authentication: plain
      enable_starttls_auto: true
  social:
    facebook_app_id: <%= ENV["FACEBOOK_APP_ID"] %>
    facebook_app_secret: <%= ENV["FACEBOOK_APP_SECRET"] %>
    google_client_id: <%= ENV["GOOGLE_CLIENT_ID"] %>
    google_client_secret: <%= ENV["GOOGLE_CLIENT_SECRET"] %>
    linkedin_client_id: <%= ENV["LINKEDIN_CLIENT_ID"] %>
    linkedin_client_secret: <%= ENV["LINKEDIN_CLIENT_SECRET"] %>
  url_with_port: http://shadowfax_production_host
